#pragma once

#include <SDL2/SDL.h>

#define KEYS_SIZE 38

namespace luv
{
  enum KeyCode
  {
    A = SDL_SCANCODE_A,
    B = SDL_SCANCODE_B,
    C = SDL_SCANCODE_C,
    D = SDL_SCANCODE_D,
    E = SDL_SCANCODE_E,
    F = SDL_SCANCODE_F,
    G = SDL_SCANCODE_G,
    H = SDL_SCANCODE_H,
    I = SDL_SCANCODE_I,
    J = SDL_SCANCODE_J,
    K = SDL_SCANCODE_K,
    L = SDL_SCANCODE_L,
    M = SDL_SCANCODE_M,
    N = SDL_SCANCODE_N,
    O = SDL_SCANCODE_O,
    P = SDL_SCANCODE_P,
    Q = SDL_SCANCODE_Q,
    R = SDL_SCANCODE_R,
    S = SDL_SCANCODE_S,
    T = SDL_SCANCODE_T,
    U = SDL_SCANCODE_U,
    V = SDL_SCANCODE_V,
    W = SDL_SCANCODE_W,
    X = SDL_SCANCODE_X,
    Y = SDL_SCANCODE_Y,
    Z = SDL_SCANCODE_Z,
    NUMBER_0 = SDL_SCANCODE_0,
    NUMBER_1 = SDL_SCANCODE_1,
    NUMBER_2 = SDL_SCANCODE_2,
    NUMBER_3 = SDL_SCANCODE_3,
    NUMBER_4 = SDL_SCANCODE_4,
    NUMBER_5 = SDL_SCANCODE_5,
    NUMBER_6 = SDL_SCANCODE_6,
    NUMBER_7 = SDL_SCANCODE_7,
    NUMBER_8 = SDL_SCANCODE_8,
    NUMBER_9 = SDL_SCANCODE_9,
    ESCAPE = SDL_SCANCODE_ESCAPE,
    SPACE = SDL_SCANCODE_SPACE,
    LEFT = SDL_SCANCODE_LEFT,
    RIGHT = SDL_SCANCODE_RIGHT,
    UP = SDL_SCANCODE_UP,
    DOWN = SDL_SCANCODE_DOWN
  };

  enum KeyState
  {
    KEY_NULL = 0,
    KEY_PRESSED,
    KEY_HOLD,
    KEY_RELEASED,
    KEY_RELEASE
  };
}
