// SDL2
#define SDL_MAIN_HANDLED
// graphics
#include <engine/graphics/renderer.hpp>
#include <engine/graphics/texture.hpp>
#include <engine/graphics/color.hpp>
#include <engine/graphics/renderable.hpp>
#include <engine/graphics/font.hpp>
// events
#include <engine/events/keyEvent.hpp>
#include <engine/events/event.hpp>
#include <engine/events/eventManager.hpp>
// core
#include <engine/core/keys.hpp>
#include <engine/core/mouse.hpp>
#include <engine/core/clock.hpp>
#include <engine/core/camera.hpp>
#include <engine/core/time.hpp>
#include <engine/core/luv_math.hpp>
// engine
#include <engine/window.hpp>
#include <engine/application.hpp>
// assets
#include <engine/assets/assetsManager.hpp>
